# Generated by Django 6.1 on 2026-09-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'Sem 1'), ('2', 'Sem 2'), ('3', 'Sem 3'), ('4', 'Sem 4'), ('5', 'Sem 5'), ('6', 'Sem 6'), ('7', 'Sem 7'), ('8', 'Sem 8')], max_length=1, null=True),
        ),
    ]
